test: &test
  adapter: postgresql
  database: test_upload_time_test
  host: localhost
  pool: 5
  timeout: 5000

development:
  adapter: postgresql
  database: test_upload_time_development
  host: localhost
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  encoding: unicode
  database: myapp_production
  pool: 5
  username: myapp
  password:
